"""d1: icd10 catalog

Revision ID: 02b47ec32ac5
Revises: 7ea1311aa729
Create Date: 2026-08-12 03:37:50.166475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '02b47ec32ac5'
down_revision: Union[str, None] = '7ea1311aa729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icd10_code',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('label_en', sa.String(length=300), nullable=False),
    sa.Column('label_ar', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )


def downgrade() -> None:
    op.drop_table('icd10_code')
