"""phase07: recall dismissed

Revision ID: 2a7dbb4d3c67
Revises: aac5aae87ec1
Create Date: 2026-08-11 01:43:02.671625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7dbb4d3c67'
down_revision: Union[str, None] = 'aac5aae87ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('recall_dismissed_until', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'recall_dismissed_until')
    # ### end Alembic commands ###
