"""a1: roles and permissions

Revision ID: 3637662c5176
Revises: 55cbd38d8a58
Create Date: 2026-08-12 01:34:30.185068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3637662c5176'
down_revision: Union[str, None] = '55cbd38d8a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('label_ar', sa.String(length=120), nullable=False),
    sa.Column('group', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('name_ar', sa.String(length=60), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    with op.batch_alter_table("staff_user") as batch:
        batch.add_column(sa.Column("role_id", sa.Integer(), nullable=True))

    # ---- data backfill: permission catalog + system roles + user mapping
    from app.core.permissions import ALL_PERMISSIONS, PERMISSION_LABELS, PERMISSION_GROUPS, SYSTEM_ROLE_MATRIX

    bind = op.get_bind()
    permission_ids: dict[str, int] = {}
    for code in ALL_PERMISSIONS:
        label, label_ar = PERMISSION_LABELS[code]
        group = next(g for g, rows in PERMISSION_GROUPS.items() if any(r[0] == code for r in rows))
        result = bind.execute(
            sa.text(
                'INSERT INTO permission (code, label, label_ar, "group", created_at, updated_at) ' 
                "VALUES (:code, :label, :label_ar, :grp, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
            ).bindparams(code=code, label=label, label_ar=label_ar, grp=group)
        )
        permission_ids[code] = result.lastrowid

    role_ids: dict[str, int] = {}
    for role_name, meta in SYSTEM_ROLE_MATRIX.items():
        result = bind.execute(
            sa.text(
                "INSERT INTO role (name, name_ar, is_system, is_active, created_at, updated_at) "
                "VALUES (:name, :name_ar, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
            ).bindparams(name=role_name, name_ar=meta["name_ar"])
        )
        role_ids[role_name] = result.lastrowid
        for code in meta["permissions"]:
            bind.execute(
                sa.text(
                    "INSERT INTO role_permission (role_id, permission_id, created_at, updated_at) "
                    "VALUES (:role_id, :permission_id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
                ).bindparams(role_id=role_ids[role_name], permission_id=permission_ids[code])
            )

    # map existing staff users by their old enum value
    bind.execute(
        sa.text(
            "UPDATE staff_user SET role_id = "
            "(SELECT id FROM role WHERE role.name = staff_user.role)"
        )
    )

    with op.batch_alter_table("staff_user") as batch:
        batch.drop_index("ix_staff_user_role")
        batch.create_index("ix_staff_user_role_id", ["role_id"], unique=False)
        batch.create_foreign_key("fk_staff_user_role", "role", ["role_id"], ["id"])
        batch.drop_column("role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_user', sa.Column('role', sa.VARCHAR(length=9), nullable=False))
    op.drop_constraint(None, 'staff_user', type_='foreignkey')
    op.drop_index(op.f('ix_staff_user_role_id'), table_name='staff_user')
    op.create_index('ix_staff_user_role', 'staff_user', ['role'], unique=False)
    op.drop_column('staff_user', 'role_id')
    op.drop_table('role_permission')
    op.drop_table('role')
    op.drop_table('permission')
    # ### end Alembic commands ###
