"""c11: reminder markers

Revision ID: 7ea1311aa729
Revises: 94e67e91c859
Create Date: 2026-08-12 03:32:42.356469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7ea1311aa729'
down_revision: Union[str, None] = '94e67e91c859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_duplicate_group_status', table_name='duplicate_group')
    op.drop_table('duplicate_group')
    op.add_column('appointment', sa.Column('reminder_sms_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointment', sa.Column('reminder_email_sent_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'reminder_sms_sent_at')
    op.create_table('duplicate_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('primary_profile_id', sa.INTEGER(), nullable=False),
    sa.Column('profile_ids', sqlite.JSON(), nullable=False),
    sa.Column('match_reason', sa.VARCHAR(length=120), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('resolved_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['primary_profile_id'], ['patient_profile.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['staff_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_duplicate_group_status', 'duplicate_group', ['status'], unique=False)
    # ### end Alembic commands ###
