"""a2: custom fields

Revision ID: a012c8ae74ff
Revises: 3637662c5176
Create Date: 2026-08-12 01:54:25.837301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a012c8ae74ff'
down_revision: Union[str, None] = '3637662c5176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.Enum('patient', 'visit', name='custom_field_entity'), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('label_ar', sa.String(length=200), nullable=True),
    sa.Column('type', sa.Enum('text', 'textarea', 'number', 'date', 'select', 'multiselect', 'boolean', name='custom_field_type'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity', 'key', name='uq_custom_field_entity_key')
    )
    op.add_column('patient_profile', sa.Column('custom_data', sa.JSON(), nullable=True))
    op.add_column('visit', sa.Column('custom_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'custom_data')
    op.drop_column('patient_profile', 'custom_data')
    op.drop_table('custom_field')
    # ### end Alembic commands ###
