"""c6+c7: referrals + lab orders

Revision ID: b8714996dcc0
Revises: 76dea373cdae
Create Date: 2026-08-12 03:06:28.589254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8714996dcc0'
down_revision: Union[str, None] = '76dea373cdae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('lab_name', sa.String(length=200), nullable=False),
    sa.Column('tests', sa.JSON(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'received', 'results_attached', 'done', name='lab_order_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('results_attachment_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_order_order_date'), 'lab_order', ['order_date'], unique=False)
    op.create_index(op.f('ix_lab_order_patient_profile_id'), 'lab_order', ['patient_profile_id'], unique=False)
    op.create_index(op.f('ix_lab_order_status'), 'lab_order', ['status'], unique=False)
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('from_doctor_id', sa.Integer(), nullable=False),
    sa.Column('to_text', sa.String(length=200), nullable=False),
    sa.Column('place', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('referral_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'seen', 'closed', name='referral_status'), nullable=False),
    sa.Column('outcome_seen_at', sa.Date(), nullable=True),
    sa.Column('outcome_text', sa.Text(), nullable=True),
    sa.Column('outcome_updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['outcome_updated_by'], ['staff_user.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_patient_profile_id'), 'referral', ['patient_profile_id'], unique=False)
    op.create_index(op.f('ix_referral_referral_date'), 'referral', ['referral_date'], unique=False)
    op.create_index(op.f('ix_referral_status'), 'referral', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_status'), table_name='referral')
    op.drop_index(op.f('ix_referral_referral_date'), table_name='referral')
    op.drop_index(op.f('ix_referral_patient_profile_id'), table_name='referral')
    op.drop_table('referral')
    op.drop_index(op.f('ix_lab_order_status'), table_name='lab_order')
    op.drop_index(op.f('ix_lab_order_patient_profile_id'), table_name='lab_order')
    op.drop_index(op.f('ix_lab_order_order_date'), table_name='lab_order')
    op.drop_table('lab_order')
    # ### end Alembic commands ###
