"""a3: vat fields

Revision ID: cd3ba9650c1d
Revises: a012c8ae74ff
Create Date: 2026-08-12 02:02:26.944786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3ba9650c1d'
down_revision: Union[str, None] = 'a012c8ae74ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("invoice") as batch:
        batch.add_column(sa.Column("tax_rate", sa.Numeric(5, 2), nullable=False, server_default="0"))
        batch.add_column(sa.Column("tax_total", sa.Numeric(12, 2), nullable=False, server_default="0"))
        batch.add_column(sa.Column("vat_inclusive", sa.Boolean(), nullable=False, server_default=sa.text("1")))
        batch.add_column(sa.Column("vat_number", sa.String(length=64), nullable=False, server_default=""))
        batch.add_column(sa.Column("vat_exempt", sa.Boolean(), nullable=False, server_default=sa.text("0")))
    with op.batch_alter_table("invoice_item") as batch:
        batch.add_column(sa.Column("tax_rate", sa.Numeric(5, 2), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_item', 'tax_rate')
    op.drop_column('invoice', 'vat_exempt')
    op.drop_column('invoice', 'vat_number')
    op.drop_column('invoice', 'vat_inclusive')
    op.drop_column('invoice', 'tax_total')
    op.drop_column('invoice', 'tax_rate')
    # ### end Alembic commands ###
