"""phase01: idempotency_key, public_asset

Revision ID: d91b6d39bb4a
Revises: 
Create Date: 2026-08-10 21:47:40.102138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91b6d39bb4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('processing', 'succeeded', 'failed', name='idem_status'), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_idempotency_expires_at', 'idempotency_key', ['expires_at'], unique=False)
    op.create_index('uq_idempotency_owner_key', 'idempotency_key', ['owner_type', 'owner_id', 'key'], unique=True)
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('form', sa.String(length=60), nullable=False),
    sa.Column('strength', sa.String(length=60), nullable=False),
    sa.Column('default_dose', sa.String(length=120), nullable=True),
    sa.Column('default_frequency', sa.String(length=120), nullable=True),
    sa.Column('default_duration', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_medication_name_form_strength', 'medication', ['name', 'form', 'strength'], unique=True)
    op.create_table('number_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'year', name='uq_number_sequence_scope_year')
    )
    op.create_table('outbox_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('email_booking_confirmation', 'attachment_scan', name='outbox_kind'), nullable=False),
    sa.Column('aggregate_type', sa.String(length=60), nullable=False),
    sa.Column('aggregate_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'sent', 'failed', name='outbox_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_table('patient_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('locale', sa.Enum('ar', 'en', name='locale'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('print_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('locale', sa.Enum('ar', 'en', name='locale'), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sanitized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_print_template_key_locale', 'print_template', ['key', 'locale'], unique=True)
    op.create_table('public_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('clinic_logo', 'doctor_photo', 'public_image', name='public_asset_kind'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.Enum('staff', 'patient', name='token_owner_type'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_token_family_id'), 'refresh_token', ['family_id'], unique=False)
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('staff_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('full_name_ar', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('admin', 'doctor', 'secretary', name='staff_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_user_email'), 'staff_user', ['email'], unique=True)
    op.create_index(op.f('ix_staff_user_role'), 'staff_user', ['role'], unique=False)
    op.create_table('syndicate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('visit_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('default_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_account_id', sa.Integer(), nullable=True),
    sa.Column('guest_key_hash', sa.String(length=64), nullable=True),
    sa.Column('guest_name', sa.String(length=200), nullable=True),
    sa.Column('guest_contact', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='chat_status'), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unread_staff', sa.Integer(), nullable=False),
    sa.Column('unread_patient', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['staff_user.id'], ),
    sa.ForeignKeyConstraint(['patient_account_id'], ['patient_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_user_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('bio_ar', sa.Text(), nullable=True),
    sa.Column('public_asset_id', sa.Integer(), nullable=True),
    sa.Column('booking_mode', sa.Enum('slots', 'day_queue', name='booking_mode'), nullable=False),
    sa.Column('default_slot_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('day_capacity', sa.Integer(), nullable=True),
    sa.Column('slot_capacity', sa.Integer(), nullable=False),
    sa.Column('billing_mode', sa.Enum('per_visit', 'per_hour', name='billing_mode'), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_bookable_online', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['public_asset_id'], ['public_asset.id'], ),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_user_id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_staff_user_id'), 'notification', ['staff_user_id'], unique=False)
    op.create_table('patient_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('full_name_ar', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'unknown', 'prefer_not_to_say', name='gender'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('phone_alt', sa.String(length=32), nullable=True),
    sa.Column('national_id_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('no_show_count', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('syndicate_id', sa.Integer(), nullable=True),
    sa.Column('syndicate_member_no', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['patient_account.id'], ),
    sa.ForeignKeyConstraint(['syndicate_id'], ['syndicate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_profile_account_id'), 'patient_profile', ['account_id'], unique=False)
    op.create_index(op.f('ix_patient_profile_code'), 'patient_profile', ['code'], unique=True)
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_ref', sa.String(length=12), nullable=False),
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('visit_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('booked', 'checked_in', 'in_progress', 'completed', 'cancelled', 'no_show', name='appointment_status'), nullable=False),
    sa.Column('source', sa.Enum('public', 'staff', 'walk_in', name='appointment_source'), nullable=False),
    sa.Column('follow_up_of_id', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('cancelled_by', sa.String(length=40), nullable=True),
    sa.Column('reminder_link_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booked_by_staff_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booked_by_staff_id'], ['staff_user.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['follow_up_of_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profile.id'], ),
    sa.ForeignKeyConstraint(['visit_type_id'], ['visit_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_booking_ref'), 'appointment', ['booking_ref'], unique=True)
    op.create_index(op.f('ix_appointment_date'), 'appointment', ['date'], unique=False)
    op.create_index('ix_appointment_doctor_date_status', 'appointment', ['doctor_id', 'date', 'status'], unique=False)
    op.create_index(op.f('ix_appointment_doctor_id'), 'appointment', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointment_patient_profile_id'), 'appointment', ['patient_profile_id'], unique=False)
    op.create_index(op.f('ix_appointment_status'), 'appointment', ['status'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('patient', 'secretary', 'system', 'ai', name='chat_sender_type'), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_conversation_id'), 'chat_message', ['conversation_id'], unique=False)
    op.create_table('doctor_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_schedule_doctor_id'), 'doctor_schedule', ['doctor_id'], unique=False)
    op.create_table('price_list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_type_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['visit_type_id'], ['visit_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_price_visit_doctor', 'price_list_item', ['visit_type_id', 'doctor_id'], unique=True)
    op.create_table('schedule_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_block_doctor_id'), 'schedule_block', ['doctor_id'], unique=False)
    op.create_table('syndicate_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('syndicate_id', sa.Integer(), nullable=False),
    sa.Column('visit_type_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('syndicate_coverage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('patient_share', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['syndicate_id'], ['syndicate.id'], ),
    sa.ForeignKeyConstraint(['visit_type_id'], ['visit_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_syndicate_price', 'syndicate_price', ['syndicate_id', 'visit_type_id', 'doctor_id'], unique=True)
    op.create_table('queue_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('visit_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'called', 'in_room', 'completed', 'left', name='queue_status'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profile.id'], ),
    sa.ForeignKeyConstraint(['visit_type_id'], ['visit_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_queue_doctor_date_seq', 'queue_entry', ['doctor_id', 'date', 'seq'], unique=False)
    op.create_index(op.f('ix_queue_entry_date'), 'queue_entry', ['date'], unique=False)
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('queue_entry_id', sa.Integer(), nullable=True),
    sa.Column('visit_type_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('vitals', sa.JSON(), nullable=True),
    sa.Column('clinical_exam', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('labs', sa.Text(), nullable=True),
    sa.Column('imaging', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('notes_next_visit', sa.Text(), nullable=True),
    sa.Column('notes_private', sa.Text(), nullable=True),
    sa.Column('follow_up_weeks', sa.Integer(), nullable=True),
    sa.Column('follow_up_due', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'completed', name='visit_status'), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('last_saved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['last_saved_by'], ['staff_user.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profile.id'], ),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['queue_entry.id'], ),
    sa.ForeignKeyConstraint(['visit_type_id'], ['visit_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_doctor_id'), 'visit', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_visit_follow_up_due'), 'visit', ['follow_up_due'], unique=False)
    op.create_index(op.f('ix_visit_patient_profile_id'), 'visit', ['patient_profile_id'], unique=False)
    op.create_index('ix_visit_profile_created', 'visit', ['patient_profile_id', 'created_at'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('lab', 'imaging', 'report', 'photo', 'other', name='attachment_kind'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('thumb_path', sa.String(length=500), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('scan_status', sa.Enum('pending', 'clean', 'rejected', name='scan_status'), nullable=False),
    sa.Column('uploaded_by_type', sa.Enum('staff', name='uploader_type'), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profile.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_patient_profile_id'), 'attachment', ['patient_profile_id'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('syndicate_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('patient_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('syndicate_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refunded_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('issued', 'partially_paid', 'paid', 'refunded', 'cancelled', name='invoice_status'), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['staff_user.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profile.id'], ),
    sa.ForeignKeyConstraint(['syndicate_id'], ['syndicate.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_index(op.f('ix_invoice_number'), 'invoice', ['number'], unique=True)
    op.create_index(op.f('ix_invoice_patient_profile_id'), 'invoice', ['patient_profile_id'], unique=False)
    op.create_table('prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['staff_user.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_table('visit_diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('differential', 'final', name='diagnosis_kind'), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('icd10_code', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_diagnosis_visit_id'), 'visit_diagnosis', ['visit_id'], unique=False)
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('percent', 'fixed', name='discount_kind'), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['staff_user.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_invoice_id'), 'discount', ['invoice_id'], unique=False)
    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('description_ar', sa.String(length=300), nullable=True),
    sa.Column('qty', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('visit_type_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_type_id'], ['visit_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_item_invoice_id'), 'invoice_item', ['invoice_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('cash', 'card', 'fawry', 'instapay', 'wallet', 'meeza', name='payment_method'), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_refund', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by'], ['staff_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_invoice_id'), 'payment', ['invoice_id'], unique=False)
    op.create_table('prescription_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.Column('free_text', sa.String(length=300), nullable=True),
    sa.Column('dose', sa.String(length=120), nullable=False),
    sa.Column('frequency', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.String(length=60), nullable=False),
    sa.Column('instructions', sa.String(length=300), nullable=True),
    sa.Column('quantity', sa.String(length=60), nullable=True),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_item_prescription_id'), 'prescription_item', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_item_prescription_id'), table_name='prescription_item')
    op.drop_table('prescription_item')
    op.drop_index(op.f('ix_payment_invoice_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_invoice_item_invoice_id'), table_name='invoice_item')
    op.drop_table('invoice_item')
    op.drop_index(op.f('ix_discount_invoice_id'), table_name='discount')
    op.drop_table('discount')
    op.drop_index(op.f('ix_visit_diagnosis_visit_id'), table_name='visit_diagnosis')
    op.drop_table('visit_diagnosis')
    op.drop_table('prescription')
    op.drop_index(op.f('ix_invoice_patient_profile_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_number'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_attachment_patient_profile_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_index('ix_visit_profile_created', table_name='visit')
    op.drop_index(op.f('ix_visit_patient_profile_id'), table_name='visit')
    op.drop_index(op.f('ix_visit_follow_up_due'), table_name='visit')
    op.drop_index(op.f('ix_visit_doctor_id'), table_name='visit')
    op.drop_table('visit')
    op.drop_index(op.f('ix_queue_entry_date'), table_name='queue_entry')
    op.drop_index('ix_queue_doctor_date_seq', table_name='queue_entry')
    op.drop_table('queue_entry')
    op.drop_index('uq_syndicate_price', table_name='syndicate_price')
    op.drop_table('syndicate_price')
    op.drop_index(op.f('ix_schedule_block_doctor_id'), table_name='schedule_block')
    op.drop_table('schedule_block')
    op.drop_index('uq_price_visit_doctor', table_name='price_list_item')
    op.drop_table('price_list_item')
    op.drop_index(op.f('ix_doctor_schedule_doctor_id'), table_name='doctor_schedule')
    op.drop_table('doctor_schedule')
    op.drop_index(op.f('ix_chat_message_conversation_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_appointment_status'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_patient_profile_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_doctor_id'), table_name='appointment')
    op.drop_index('ix_appointment_doctor_date_status', table_name='appointment')
    op.drop_index(op.f('ix_appointment_date'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_booking_ref'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_patient_profile_code'), table_name='patient_profile')
    op.drop_index(op.f('ix_patient_profile_account_id'), table_name='patient_profile')
    op.drop_table('patient_profile')
    op.drop_index(op.f('ix_notification_staff_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_table('doctor')
    op.drop_table('chat_conversation')
    op.drop_table('visit_type')
    op.drop_table('syndicate')
    op.drop_index(op.f('ix_staff_user_role'), table_name='staff_user')
    op.drop_index(op.f('ix_staff_user_email'), table_name='staff_user')
    op.drop_table('staff_user')
    op.drop_table('setting')
    op.drop_index(op.f('ix_refresh_token_family_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_table('public_asset')
    op.drop_index('uq_print_template_key_locale', table_name='print_template')
    op.drop_table('print_template')
    op.drop_table('patient_account')
    op.drop_table('outbox_event')
    op.drop_table('number_sequence')
    op.drop_index('uq_medication_name_form_strength', table_name='medication')
    op.drop_table('medication')
    op.drop_index('uq_idempotency_owner_key', table_name='idempotency_key')
    op.drop_index('ix_idempotency_expires_at', table_name='idempotency_key')
    op.drop_table('idempotency_key')
    # ### end Alembic commands ###
