"""f: hr

Revision ID: ecaf63850de2
Revises: 4ff8384f937a
Create Date: 2026-08-12 03:54:29.372187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ecaf63850de2'
down_revision: Union[str, None] = '4ff8384f937a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_user_id', 'date', name='uq_attendance_day')
    )
    op.create_index(op.f('ix_attendance_record_date'), 'attendance_record', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_record_staff_user_id'), 'attendance_record', ['staff_user_id'], unique=False)
    op.create_table('leave_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=40), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leave_status'), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['staff_user.id'], ),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_request_staff_user_id'), 'leave_request', ['staff_user_id'], unique=False)
    op.create_index(op.f('ix_leave_request_status'), 'leave_request', ['status'], unique=False)
    op.create_table('payroll_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('draft', 'paid', name='payroll_status'), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['staff_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_run_month'), 'payroll_run', ['month'], unique=True)
    op.create_table('payroll_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('staff_user_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('social_insurance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_line_item_payroll_run_id'), 'payroll_line_item', ['payroll_run_id'], unique=False)
    op.add_column('staff_user', sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('staff_user', sa.Column('allowances', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('staff_user', sa.Column('deductions', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('staff_user', sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('staff_user', sa.Column('social_insurance', sa.Numeric(precision=12, scale=2), nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_user', 'tax_pct')
    op.drop_column('staff_user', 'deductions')
    op.drop_column('staff_user', 'allowances')
    op.drop_column('staff_user', 'base_salary')
    op.drop_index(op.f('ix_payroll_line_item_payroll_run_id'), table_name='payroll_line_item')
    op.drop_table('payroll_line_item')
    op.drop_index(op.f('ix_payroll_run_month'), table_name='payroll_run')
    op.drop_table('payroll_run')
    op.drop_index(op.f('ix_leave_request_status'), table_name='leave_request')
    op.drop_index(op.f('ix_leave_request_staff_user_id'), table_name='leave_request')
    op.drop_table('leave_request')
    op.drop_index(op.f('ix_attendance_record_staff_user_id'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_date'), table_name='attendance_record')
    op.drop_table('attendance_record')
    # ### end Alembic commands ###
