"""c3: communication log

Revision ID: f20195d56379
Revises: 27c49033a18d
Create Date: 2026-08-12 02:49:09.933756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20195d56379'
down_revision: Union[str, None] = '27c49033a18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('call', 'email', 'whatsapp', 'sms', 'in_person', name='comm_channel'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_log_entry_channel'), 'communication_log_entry', ['channel'], unique=False)
    op.create_index(op.f('ix_communication_log_entry_patient_profile_id'), 'communication_log_entry', ['patient_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('petty_cash_transaction', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('petty_cash_transaction', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('expense', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('expense', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('activity_event', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('activity_event', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_communication_log_entry_patient_profile_id'), table_name='communication_log_entry')
    op.drop_index(op.f('ix_communication_log_entry_channel'), table_name='communication_log_entry')
    op.drop_table('communication_log_entry')
    # ### end Alembic commands ###
