"""phase01: audit tables

Revision ID: d37a006f4896
Revises: 
Create Date: 2026-08-10 21:47:03.912841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37a006f4896'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_checkpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('first_event_id', sa.Integer(), nullable=False),
    sa.Column('last_event_id', sa.Integer(), nullable=False),
    sa.Column('chain_head_hash', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=256), nullable=False),
    sa.Column('public_key_id', sa.String(length=64), nullable=False),
    sa.Column('export_path', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_checkpoint_last_event', 'audit_checkpoint', ['last_event_id'], unique=False)
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_type', sa.Enum('staff', 'patient', 'system', name='audit_actor_type'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.Enum('intent', 'committed', 'aborted', 'access', name='audit_outcome'), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_audit_event_action'), 'audit_event', ['action'], unique=False)
    op.create_index(op.f('ix_audit_event_correlation_id'), 'audit_event', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_event_entity_type'), 'audit_event', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_event_occurred_at'), 'audit_event', ['occurred_at'], unique=False)
    op.create_table('audit_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genesis_hash', sa.String(length=64), nullable=False),
    sa.Column('last_hash', sa.String(length=64), nullable=False),
    sa.Column('last_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_meta')
    op.drop_index(op.f('ix_audit_event_occurred_at'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_entity_type'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_correlation_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_action'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index('ix_audit_checkpoint_last_event', table_name='audit_checkpoint')
    op.drop_table('audit_checkpoint')
    # ### end Alembic commands ###
